### ISSUE TITLE
Problema installazione

### ISSUE THREAD

**Issue by marcogiannini** [egdoc/com.github.egdoc.GoSign#1]
Provando ad installare mi compare il seguente errore

```
flatpak-builder --user --install --install-deps-from=flathub build-dir com.github.egdoc.GoSign.yml --force-clean

(flatpak-builder:18162): flatpak-builder-ERROR **: 17:17:51.002: Failed to load included manifest (/home/marco/com.github.egdoc.GoSign/shared-modules/libusb/libusb.json): Apertura del file «/home/marco/com.github.egdoc.GoSign/shared-modules/libusb/libusb.json» non riuscita: File o directory non esistente
Rilevato trace/breakpoint (core dump creato)
```

**Comment by egdoc** [comment]
Occorre clonare il repo includendo i submodules. Sono dei moduli condivisi da flathub che forniscono le istruzioni per compilare alcune librerie.

**Comment by marcogiannini** [comment]
Mi ero dimenticato di clonare tutto.
Allora, il problema del mancato avvio con crash continua a presentarsi e sono costretto a usare il parametro _--in-process-gpu_ per avviarlo (vedi https://www.marcosbox.org/2022/05/gosign-desktop-risolvere-crash-linux.html)
![Schermata del 2023-05-19 21-33-15](https://github.com/egdoc/com.github.egdoc.GoSign/assets/4943897/920836ac-5ce7-4f33-ad61-d3b00699abf9)

Una volta fatto continua a non rilevare il dispositivo di firma

**Comment by egdoc** [comment]
Strano, a me si avvia senza problemi sia su Fedora38 che su Ubuntu 22.04, sembra non esserci bisogno di usare _--in-process-gpu_. Ho notato che il pacchetto deb contiene alcune regole udev, puo essere che siano coinvolte nel rilevamento dei dispositivi di firma. Intanto chiudo questa issue, magari ne apriamo una dedicata. Grazie.

**Comment by marcogiannini** [comment]
Riguardo l'errore all'avvio, nel tuo caso che scheda video e driver utilizzi?

**Comment by egdoc** [comment]
Scheda video Intel integrata:
`00:02.0 VGA compatible controller: Intel Corporation HD Graphics 620 (rev 02)`

**Comment by egdoc** [comment]
Ad ogni modo, ho creato un piccolo wrapper che copia le regole udev presenti nel pacchetto .deb e fai il build/installa il flatpak. Appena puoi/vuoi sono curioso di verificare che fosse quello il problema e che adesso GoSign vede la business key. Grazie

**Comment by marcogiannini** [comment]
Niente, continua a dare entrambi gli errori, sia il mancato avvio senza il parametro, sia il non rilevamento del dispositivo di firma

`marco@pop-os:~$ flatpak run com.github.egdoc.GoSign --in-process-gpu
Creating certificate store: {"filename":"/home/marco/.gosign/certificates.db","autoload":true}
Creating option store: {"filename":"/home/marco/.gosign/options.db","autoload":true}
Creating Google Analytics Client
2023-07-02T15:16:39.291Z warn [DikeClients]: LIBRARY PATH __dirname IS STILL BROKEN, PLEASE CHECK ISSUE ON GITHUB!!!
      https://github.com/electron/electron/issues/8206
2023:07:02 17:16:39 (0xfeeb4a80)[INFO][dgs] (prepare_tempdir): Removing session dir /home/marco/.gosign/sessiondir_2e362707
Scheduler -> getMessages 
Registering channel get-version
Registering channel jobs-channel
Registering channel add-jobs-channel
Registering channel test-pin
Registering channel set-configuration
Registering channel get-session-params
Registering channel device-list
Registering channel change-pin
Registering channel unlock-pin
Registering channel unlock-ce-pin
Registering channel device-activate
Registering channel device-activate-ce
Registering channel device-send-otp-ce
Registering channel authorize-ce
Registering channel admin-secrets-ce
Registering channel select-file
Registering channel load-file
Registering channel load-file-buffer
Registering channel load-file-utf8
Registering channel save-asset
Registering channel save-file
Registering channel save-file-utf8
Registering channel pdf-image-combine
Registering channel copy-file
Registering channel get-user-folders
Registering channel double-pin
Registering channel load-asset
Registering channel remove-asset
Registering channel remove-file
Registering channel open-file-os
Registering channel get-user-home
Registering channel remote-signature-fsm-init
Registering channel remote-signature-fsm-otp
Registering channel remote-signature-fsm-auth
Registering channel remote-signature-delete-cert
Registering channel ts-fsm-init
Registering channel ts-fsm-auth
Registering channel ts-remove
Registering channel ts-get
Registering channel signature-init
Registering channel signature-sign
Registering channel file-save-selection
Registering channel license-validate
Registering channel license-status
Registering channel license-deactivate
Registering channel license-remove
Registering channel app-path
Registering channel signature-validate
Registering channel signature-parse-result
Registering channel signature-start
Registering channel signature-otp
Registering channel signature-contacts
Registering channel signature-resend-sms
Registering channel signature-remote-status
Registering channel web-signature-send-cert
Registering channel web-signature-send-auth
Registering channel web-signature-start-signing
Registering channel signature-remote-status
Found duplicate channel signature-remote-status, skipping...
Registering channel app-dir
Registering channel get-european-tsl
Registering channel add-european-tsl
Registering channel remove-european-tsl
Registering channel check-updates-european-tsl
Registering channel update-european-tsl
Registering channel web-signature-otp
Registering channel web-signature-remote-status
Registering channel web-signature-resend-sms
Registering channel signature-abort
Registering channel web-signature-abort
Registering channel verify-init
Registering channel verify-perform
Registering channel verify-miss-tsl
Registering channel verify-detached-sources
Registering channel verify-perform-at-date
Registering channel verify-abort
Registering channel authentication-ask
Registering channel authentication-identity
Registering channel authentication-logout
Registering channel gosignweb-sendandsign
Registering channel gosignweb-signbook
Registering channel gosignweb-createenvelope
Registering channel updater-check
Registering channel updater-init
Registering channel updater-update
Registering channel path-parse
Registering channel path-join
Registering channel paths-is-dir
Registering channel folder-exist
Registering channel file-exist
Registering channel add-p12
Registering channel remove-p12
Registering channel get_atl
Registering channel timestamp-validate
Registering channel timestamp-fsm-init
Registering channel timestamp-fsm-perform
Registering channel timestamp-fsm-abort
Registering channel associate-validate
Registering channel associate-files
Registering channel separate-file
Registering channel verify-report
Registering channel encipher-fsm-init
Registering channel encipher-fsm-perform
Registering channel encipher-fsm-abort
Registering channel decipher-fsm-init
Registering channel decipher-fsm-perform
Registering channel certificate-history-list
Registering channel certificate-history-os-open
Registering channel certificate-history-remove-cert
Registering channel encipher-validate
Registering channel verify-extract
Registering channel verify-extract-files
Registering channel renew-channel-pin
Registering channel open-certificate
Registering channel set-webserver-status
Registering channel web-signature-confirm
Registering channel bk-drivers
Registering channel embedded-drivers
Registering channel bk-drivers-path
Registering channel embedded-drivers-path
Registering channel check-firefox
Registering channel open-firefox
Registering channel install-firefox
Registering channel make-zip
Registering channel check-pdf
Registering channel emission-channel-raopin
Registering channel emission-channel-scpin
Registering channel emission-channel-trashcerts
Registering channel emission-channel-start-signing
Registering channel emission-channel-otp
Registering channel emission-channel-remote-status
Registering channel emission-channel-resend-sms
Registering channel emission-channel-abort
Registering channel analytics_event
Registering channel check-connection
Registering channel vscr-insert-card
Registering channel vscr-remove-card
Registering channel vscr-get-status-card
Registering channel vscr-signature-send-auth
Registering channel vscr-signature-otp
Registering channel vscr-signature-remote-status
Registering channel vscr-signature-resend-sms
Registering channel vscr-signature-abort
Registering channel vscr-signature-start-signing
Registering channel set-custom-p11
Registering channel unset-custom-p11
Gtk-Message: 17:16:39.652: Failed to load module "canberra-gtk-module"
Gtk-Message: 17:16:39.652: Failed to load module "canberra-gtk-module"
Desktop screen sizes {
  screenW: 1920,
  screenH: 1048,
  biggerStartSize: true,
  minWidth: 980,
  minHeight: 746
}
(electron) The default value of app.allowRendererProcessReuse is deprecated, it is currently "false".  It will change to be "true" in Electron 9.  For more information please check https://github.com/electron/electron/issues/18397
🚀 ~ setupCustomization { customization: 'standard', hasCustomBackgrounds: undefined }
Binding observable to channel core-messages
Binding observable to channel authentication-update
Binding observable to channel diker-web-sign
Registering channel get-configuration
Binding observable to channel routing
Building menu..
Menu build complete
Scheduler -> getMessages 
🚀 ~ Analytics ~ currentCustomization standard
Creating ua instance {
  GoogleUa: 'UA-74315539-6',
  clientID: '51cb4a82-8aec-47fd-869e-1ad29269f979'
}
🚀 ~ Analytics ~  customMetric cd3
🚀 ~ Analytics ~ visitor {
  _queue: [],
  options: { tid: 'UA-74315539-6', cid: '51cb4a82-8aec-47fd-869e-1ad29269f979' },
  _context: {},
  _persistentParams: { mobileDeviceBranding: 'standard', cd3: '1' },
  tid: 'UA-74315539-6',
  cid: '51cb4a82-8aec-47fd-869e-1ad29269f979'
}
Logged false
Setting Logged metric to false
Building menu..
Menu build complete
PRO false
Setting PRO metric to false
2023-07-02T15:16:40.705Z warn [Gui.HeaderService]: This method is deprecated.
PRO false
Setting PRO metric to false
2023-07-02T15:16:40.827Z warn [Gui.HeaderService]: This method is deprecated.
HeartBeat message
Sending ScreenView {"type":"screenview","an":"GoSign Desktop","av":"1.3.10","ua":"GoSign Desktop/1.3.10 (Linux)","fl":"install.linux.peruser","aiid":"ARCHITETTURA OS LOCALE: 64 bit","cd":"MainWindow"}
🚀 ~ Uploader ~ sendGA4Event ~ body https://www.google-analytics.com/mp/collect?measurement_id=G-DRD68ZTZCV&api_secret=ueftVD8GQXu801F96WhCcg {"client_id":"1505783504.1674490861","user_id":"51cb4a82-8aec-47fd-869e-1ad29269f979","events":[{"name":"page_view","params":{"gcs":"G111","ad_storage":"granted","analytics_storage":"granted","ads_data_redaction":true,"engagement_time_msec":1,"event_action":"page_view","event_category":"screenview","event_label":"StartApp","page_title":"MainWindow","page_location":"https://gosign.it","mobileDeviceBranding":"standard","customization":"standard","cd3":"1","logged":"0","cd1":"0","isPRO":"0","cd2":"0","appName":"GoSign Desktop","appVersion":"1.3.10","installationType":"install.linux.peruser","userAgent":"GoSign Desktop/1.3.10 (Linux)","architectureString":"ARCHITETTURA OS LOCALE: 64 bit"}}]}
Message sent to analytics
Initializing generic fsm for 6
Sending  'DGS_EVT_UPDATE_CHECK_REQUESTED', to fsm of type DGS_FLOW_UPDATECHECK: {"version":"1.3.10"}
{ version: '1.3.10' }
Retrieving Atl chains { forced: true }
2023-07-02T15:16:53.020Z warn [Gui.HeaderService]: This method is deprecated.
{ countries: [] }


`
